# Generated by Django 4.2.3 on 2023-09-07 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('commentaire', models.TextField(max_length=200)),
                ('animaux', models.ManyToManyField(choices=[('chien', 'Chien'), ('chat', 'Chat'), ('poule', 'Poule'), ('oiseau', 'Oiseau'), ('lapin', 'Lapin'), ('poisson', 'Poisson'), ('autre', 'Autre')], to='info.animal')),
                ('besoins', models.ManyToManyField(related_name='proprietaires', to='info.service')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ville', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('photo_de_profil', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('tarifs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('references', models.DecimalField(decimal_places=2, max_digits=3)),
                ('commentaire', models.TextField(max_length=200)),
                ('type_services', models.ManyToManyField(related_name='prestataires', to='info.service')),
            ],
        ),
    ]
